#!/bin/bash
# Fetch secret name from CLI Args
SECRET_NAME="$1"
if [ -z "$SECRET_NAME" ] ; then
    echo "Must provide a Secret name!"
    exit 1
fi

# Verify dependencies
if [ -z $(which jq) ] ; then
    echo "Application jq required to use this tool!"
    exit 1
fi
if [ -z $(which kubectl) ] ; then
    echo "Application kubectl required to use this tool!"
    exit 1
fi

kubectl get secrets "$SECRET_NAME" -o json | jq -r '.data | to_entries[] | "\(.key)\t\(.value)"' |
  while IFS=$'\t' read KEY VALUE
  do
    DECODED=$(printf "%s" "$VALUE" | base64 --decode)
    echo "${KEY}: ${DECODED}"
  done
