name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Create Release and Publish Artifacts
    runs-on: ubuntu-latest

    env:
      ARTIFACT_DIR: dist
      ARCHIVE_PATH: dist/kubesecrets.tar.gz

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Prepare Files
        run: |
          mkdir -p $ARTIFACT_DIR/kubesecrets
          cp kubesecrets $ARTIFACT_DIR/kubesecrets/
          tar -czf $ARCHIVE_PATH -C $ARTIFACT_DIR kubesecrets

      - name: Generate Checksum
        run: |
          sha256sum $ARCHIVE_PATH > $ARTIFACT_DIR/sha256sum.txt
          echo "SHA256=$(cut -d ' ' -f1 $ARTIFACT_DIR/sha256sum.txt)" >> $GITHUB_ENV

      - name: Extract Release Notes
        id: changelog
        uses: coditory/changelog-parser@v1

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: "kubesecrets ${{ github.ref_name }}"
          draft: false
          prerelease: false
          body: ${{ steps.changelog.outputs.description }}
          files: |
            ${{ env.ARCHIVE_PATH }}
            ${{ env.ARTIFACT_DIR }}/sha256sum.txt

      - name: Configure SSH for Deploy Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOMEBREW_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
            
      - name: Checkout Homebrew Tap Repo
        uses: actions/checkout@v4
        with:
          repository: cclose/homebrew-tap
          path: homebrew-tap
          ssh-key: ${{ secrets.HOMEBREW_DEPLOY_KEY }}

      - name: Update Homebrew Tap
        run: |
          cd homebrew-tap

          FORMULA_PATH=Formula/kubesecrets.rb
          TAG_VERSION="${{ github.ref_name }}"

          sed -i "s|^  url \".*\"|  url \"https://github.com/cclose/kubesecrets/releases/download/${TAG_VERSION}/kubesecrets.tar.gz\"|" $FORMULA_PATH
          sed -i "s|^  sha256 \".*\"|  sha256 \"${SHA256}\"|" $FORMULA_PATH
          sed -i "s|^  version \".*\"|  version \"${TAG_VERSION#v}\"|" $FORMULA_PATH || true

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Update kubesecrets formula to ${TAG_VERSION}"
          git push
